import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { apiUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { sanitizePostHtml } from "@/lib/content";
import { slugify } from "@/lib/security";
import { sameOrigin } from "@/lib/request";
const payload=z.object({title:z.string().min(1).max(180),slug:z.string().max(190),excerpt:z.string().max(500),content_json:z.string(),content_html:z.string(),cover_image:z.string().max(1000).optional().default(""),cover_alt:z.string().max(250).optional().default(""),category_id:z.number().int().positive().nullable().optional(),tags_text:z.string().max(500),seo_title:z.string().max(180),seo_description:z.string().max(300),scheduled_at:z.string().nullable().optional()});
export async function GET(_:NextRequest,{params}:{params:Promise<{id:string}>}){const user=await apiUser();if(!user)return NextResponse.json({error:"Não autorizado"},{status:401});const {id}=await params;const post=db.prepare("SELECT * FROM posts WHERE id=?").get(id) as {author_id:number}|undefined;if(!post||(user.role!=="admin"&&post.author_id!==user.id))return NextResponse.json({error:"Não encontrado"},{status:404});return NextResponse.json(post)}
export async function PUT(request:NextRequest,{params}:{params:Promise<{id:string}>}){const user=await apiUser();if(!user)return NextResponse.json({error:"Não autorizado"},{status:401});if(!sameOrigin(request))return NextResponse.json({error:"Origem inválida"},{status:403});const {id}=await params;const existing=db.prepare("SELECT * FROM posts WHERE id=?").get(id) as {author_id:number;status:string}|undefined;if(!existing||(user.role!=="admin"&&existing.author_id!==user.id))return NextResponse.json({error:"Não encontrado"},{status:404});if(user.role!=="admin"&&!["rascunho","alteracoes_solicitadas"].includes(existing.status))return NextResponse.json({error:"Este artigo está em revisão e não pode ser alterado."},{status:409});const parsed=payload.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:"Campos inválidos"},{status:400});const p=parsed.data;let slug=slugify(p.slug||p.title);const conflict=db.prepare("SELECT id FROM posts WHERE slug=? AND id<>?").get(slug,id);if(conflict)slug=`${slug}-${id}`;db.prepare(`UPDATE posts SET title=?,slug=?,excerpt=?,content_json=?,content_html=?,cover_image=?,cover_alt=?,category_id=?,tags_text=?,seo_title=?,seo_description=?,scheduled_at=?,updated_at=? WHERE id=?`).run(p.title,slug,p.excerpt,p.content_json,sanitizePostHtml(p.content_html),p.cover_image||null,p.cover_alt,p.category_id||null,p.tags_text,p.seo_title,p.seo_description,p.scheduled_at||null,new Date().toISOString(),id);return NextResponse.json({id:Number(id),slug})}
export async function DELETE(_:NextRequest,{params}:{params:Promise<{id:string}>}){const user=await apiUser("admin");if(!user)return NextResponse.json({error:"Não autorizado"},{status:401});const {id}=await params;db.prepare("UPDATE posts SET status='arquivado',updated_at=? WHERE id=?").run(new Date().toISOString(),id);return NextResponse.json({ok:true})}
