import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { apiUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { sanitizePostHtml } from "@/lib/content";
import { slugify } from "@/lib/security";
import { sameOrigin } from "@/lib/request";

const payload=z.object({title:z.string().min(1).max(180),slug:z.string().max(190).optional().default(""),excerpt:z.string().max(500).default(""),content_json:z.string().default("{}"),content_html:z.string().default(""),cover_image:z.string().max(1000).optional().default(""),cover_alt:z.string().max(250).optional().default(""),category_id:z.number().int().positive().nullable().optional(),tags_text:z.string().max(500).default(""),seo_title:z.string().max(180).default(""),seo_description:z.string().max(300).default("")});
function uniqueSlug(title:string,requested:string){const base=slugify(requested||title)||`artigo-${Date.now()}`;let value=base;let i=2;while(db.prepare("SELECT 1 FROM posts WHERE slug=?").get(value))value=`${base}-${i++}`;return value}
export async function GET(){const user=await apiUser();if(!user)return NextResponse.json({error:"Não autorizado"},{status:401});const rows=db.prepare(`SELECT p.*,c.name category_name,u.name author_name FROM posts p LEFT JOIN categories c ON c.id=p.category_id JOIN users u ON u.id=p.author_id ${user.role==="admin"?"":"WHERE p.author_id=?"} ORDER BY p.updated_at DESC`).all(...(user.role==="admin"?[]:[user.id]));return NextResponse.json(rows)}
export async function POST(request:NextRequest){const user=await apiUser();if(!user)return NextResponse.json({error:"Não autorizado"},{status:401});if(!sameOrigin(request))return NextResponse.json({error:"Origem inválida"},{status:403});const parsed=payload.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:"Preencha o título e verifique os campos."},{status:400});const p=parsed.data;const slug=uniqueSlug(p.title,p.slug);const now=new Date().toISOString();const result=db.prepare(`INSERT INTO posts (title,slug,excerpt,content_json,content_html,cover_image,cover_alt,status,author_id,category_id,tags_text,seo_title,seo_description,created_at,updated_at) VALUES (?,?,?,?,?,?,?,'rascunho',?,?,?,?,?,?,?)`).run(p.title,slug,p.excerpt,p.content_json,sanitizePostHtml(p.content_html),p.cover_image||null,p.cover_alt,user.id,p.category_id||null,p.tags_text,p.seo_title,p.seo_description,now,now);db.prepare("INSERT INTO audit_log (user_id,action,entity,entity_id,created_at) VALUES (?,?,?,?,?)").run(user.id,"criar","post",String(result.lastInsertRowid),now);return NextResponse.json({id:Number(result.lastInsertRowid),slug})}
