"use client";

import Link from "next/link";
import { Copy, FilePlus2, Pencil, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";
import { SECTION_TEMPLATES } from "@/lib/page-builder";

type PageItem = { id: number; title: string; slug: string; status: string; is_home: number; updated_at: string; published_at: string | null };
export function AdminPagesManager({ pages }: { pages: PageItem[] }) {
  const router = useRouter(); const [open, setOpen] = useState(false); const [title, setTitle] = useState(""); const [template, setTemplate] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function create(event: FormEvent) { event.preventDefault(); setBusy(true); const response = await fetch("/api/admin/pages", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, template }) }); const data = await response.json(); if (response.ok) location.href = `/admin/paginas/${data.id}/editor`; else setMessage(data.error || "Não foi possível criar."); setBusy(false); }
  async function duplicate(id: number) { setBusy(true); const response = await fetch(`/api/admin/pages/${id}/duplicate`, { method: "POST" }); const data = await response.json(); if (response.ok) location.href = `/admin/paginas/${data.id}/editor`; else setMessage(data.error || "Não foi possível duplicar."); setBusy(false); }
  async function remove(page: PageItem) { if (!confirm(`Excluir a página “${page.title}”?`)) return; setBusy(true); const response = await fetch(`/api/admin/pages/${page.id}`, { method: "DELETE" }); const data = await response.json(); if (response.ok) router.refresh(); else setMessage(data.error || "Não foi possível excluir."); setBusy(false); }
  return <div className="stack"><div className="page-head"><div><h1 className="app-title">Páginas</h1><p className="muted">Crie páginas visuais, publique e recupere versões anteriores.</p></div><button className="btn btn-primary" onClick={() => setOpen((current) => !current)}><FilePlus2 size={18}/> Nova página</button></div>{open && <form className="panel page-create-panel" onSubmit={create}><div className="field"><label>Título da página</label><input className="input" value={title} onChange={(event) => setTitle(event.target.value)} required minLength={2}/></div><div className="field"><label>Começar com</label><select className="select" value={template} onChange={(event) => setTemplate(event.target.value)}><option value="">Página em branco</option>{SECTION_TEMPLATES.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></div><button className="btn btn-primary" disabled={busy}>Criar e editar</button></form>}{message && <p className="form-error">{message}</p>}<div className="panel"><div className="table-wrap"><table className="data-table responsive-table"><thead><tr><th>Página</th><th>Endereço</th><th>Status</th><th>Atualizada</th><th>Ações</th></tr></thead><tbody>{pages.map((page) => <tr key={page.id}><td data-label="Página"><strong>{page.title}</strong>{page.is_home ? <small className="home-page-label">Página inicial</small> : null}</td><td data-label="Endereço">{page.is_home ? "/" : `/${page.slug}`}</td><td data-label="Status"><span className={`status status-${page.status}`}>{page.status}</span></td><td data-label="Atualizada">{new Date(page.updated_at).toLocaleString("pt-BR")}</td><td data-label="Ações"><div className="actions"><Link className="btn btn-outline" href={`/admin/paginas/${page.id}/editor`}><Pencil size={16}/> Editar</Link><button className="btn btn-ghost" onClick={() => duplicate(page.id)} disabled={busy} title="Duplicar"><Copy size={16}/></button>{!page.is_home && <button className="btn btn-danger" onClick={() => remove(page)} disabled={busy} title="Excluir"><Trash2 size={16}/></button>}</div></td></tr>)}</tbody></table></div></div></div>;
}
