"use client";

import Link from "next/link";
import { Palette, PanelsTopLeft, Save, Upload } from "lucide-react";
import { useState } from "react";

type HomeBlock = { id: string; type: string; title: string; enabled: number | boolean; position: number; config_json: string };
export function GlobalAppearanceEditor({ initialSettings, blocks, homePageId }: { initialSettings: Record<string, string>; blocks: HomeBlock[]; homePageId: number }) {
  const [settings, setSettings] = useState(initialSettings); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const set = (key: string, value: string) => setSettings((current) => ({ ...current, [key]: value }));
  async function upload(file: File, key: string) { const body = new FormData(); body.append("file", file); const response = await fetch("/api/media", { method: "POST", body }); const data = await response.json(); if (response.ok) set(key, data.url); else setMessage(data.error || "Falha ao enviar imagem"); }
  async function save() { setBusy(true); setMessage("Salvando..."); const response = await fetch("/api/admin/theme", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ settings, blocks: blocks.map((block) => ({ ...block, enabled: Boolean(block.enabled) })) }) }); setMessage(response.ok ? "Aparência global atualizada." : "Não foi possível salvar."); setBusy(false); }
  return <div className="global-appearance"><div className="page-head"><div><h1 className="app-title">Aparência global</h1><p className="muted">Defina marca, cores e fontes usadas por todas as páginas.</p></div><Link className="btn btn-outline" href={`/admin/paginas/${homePageId}/editor`}><PanelsTopLeft size={18}/> Editar página inicial</Link></div><div className="settings-grid global-appearance-grid"><section className="panel stack"><div className="section-heading"><div><h2>Marca</h2><p>Logo utilizada no cabeçalho e no rodapé.</p></div></div><div className="field"><label>Nome da marca</label><input className="input" value={settings.logo_text || ""} onChange={(event) => set("logo_text", event.target.value)}/></div>{[["Logo", "logo_url"], ["Favicon", "favicon_url"]].map(([label, key]) => <div className="field" key={key}><label>{label}</label>{settings[key] && <img className="global-asset-preview" src={settings[key]} alt={label}/>}<label className="btn btn-outline"><Upload size={16}/> {settings[key] ? "Substituir" : "Enviar"}<input type="file" hidden accept="image/png,image/jpeg,image/webp" onChange={(event) => event.target.files?.[0] && upload(event.target.files[0], key)}/></label></div>)}</section><section className="panel stack"><div className="section-heading"><div><h2><Palette size={20}/> Cores e fontes</h2><p>Tokens visuais compartilhados pelo site.</p></div></div><div className="theme-color-grid">{[["Principal", "primary_color"], ["Apoio", "accent_color"], ["Fundo", "background_color"], ["Texto", "text_color"]].map(([label, key]) => <div className="field" key={key}><label>{label}</label><div className="color-field"><input type="color" value={settings[key] || "#000000"} onChange={(event) => set(key, event.target.value)}/><input className="input" value={settings[key] || ""} onChange={(event) => set(key, event.target.value)}/></div></div>)}</div><div className="theme-font-grid">{[["Fonte dos títulos", "heading_font"], ["Fonte do corpo", "body_font"]].map(([label, key]) => <div className="field" key={key}><label>{label}</label><select className="select" value={settings[key] || "Inter"} onChange={(event) => set(key, event.target.value)}>{["Hanken Grotesk", "Inter", "Arial", "Georgia"].map((font) => <option key={font}>{font}</option>)}</select></div>)}</div></section></div><div className="global-save-bar"><span aria-live="polite">{message}</span><button className="btn btn-primary" onClick={save} disabled={busy}><Save size={17}/>{busy ? "Salvando..." : "Salvar aparência"}</button></div></div>;
}
